---

  - name: Assures /etc/apache2/ssl dir exists
    sudo: yes
    file: path=/etc/apache2/ssl state=directory

  - name: Create self-signed SSL cert
    sudo: yes
    command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=US" -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt

  - name: Copy SSL apache vhost file
    synchronize: src=files/sites-enabled/default-ssl.conf dest=/etc/apache2/sites-enabled/default-ssl.conf
    sudo: yes
    tags:
      - apache
      - php-stack
      - ssl
    notify: Restart apache

  - name: Enable Apache2 SSL module
    sudo: yes
    apache2_module: state=present name=ssl
    tags:
      - apache
      - php-stack
      - ssl
    notify: Restart apache
